api_platform:
  title: Scraperrr
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  formats:
    jsonld: [ 'application/json+ld' ]
    json: [ 'application/json' ]
  docs_formats:
    jsonld: [ 'application/json+ld' ]
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: [ 'text/html' ]
    json: [ 'application/json' ]
