security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/auth
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /auth
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # JWT authentication for /api/users routes
    api_users:
      pattern: ^/api/users
      stateless: true
      provider: app_user_provider
      jwt: ~
#      enables JWT

    # Custom authenticator for /api/v1/news routes
    api_news:
      pattern: ^/api/v1/news
      stateless: true
      provider: app_user_provider
      custom_authenticator: App\Security\PersonalAccessTokenAuthenticator

    # Default fallback firewall (optional)
    main:
      pattern: ^/
      stateless: true
      provider: app_user_provider

  access_control:
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10